name: yuka
description: "A dart conversion of Yuka a library for developing Game AI."
version: 0.0.1
homepage: https://github.com/Knightro63/yuka/

topics:
  - threejs
  - games
  - ai
  - game-development
  - game-ai

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.5.0
  uuid: ^4.4.0
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

platforms:
  android:
  ios:
  macos:
  web:
  windows:
  linux: