name: examples
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_colorpicker: ^1.1.0
  url_launcher: ^6.3.2
  css:
    git:
      url: https://github.com/Knightro63/css.git
  pointer_lock:
    git:
      url: https://github.com/helgoboss/pointer_lock.git
  three_js: ^0.2.5
  three_js_helpers: ^0.2.3
  yuka:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  permission_handler_apple:
    git:
      url: https://github.com/alex-melnyk/flutter-permission-handler.git 
      path: permission_handler_apple
  file_picker: ^10.1.9
  three_js_advanced_loaders:
    path: ../../three_js/packages/three_js_advanced_loaders
  three_js_animations:
    path: ../../three_js/packages/three_js_animations
  three_js_core:
    path: ../../three_js/packages/three_js_core
  three_js_math:
    path: ../../three_js/packages/three_js_math

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/models/house/
    - assets/textures/